spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: library
  security:
    token:
      secret: qwerty
      maxAgeSeconds: 860000
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  cache:
    type: redis
  redis:
    host: 192.168.99.100